### ISSUE TITLE
Stock Control_Numbers with decimals

### ISSUE THREAD

**Issue by MonSuYee** [EyeSeeTea/SurveillanceMyanmarApp#14]
We don't need decimals in stock Control page. Even for ACT, although we chooses to recommend half or thirds of strips to volunteers, we count the remaining halfs and thirds as 1 (as if we used the whole strips, not part of them)

**Comment by ifoche** [comment]
ok, we'll remove the decimal point. Thanks

**Comment by rodmelia** [comment]
we need to clarify this - it sounds to me that it is not a matter of hiding
the decimal points.
We need to reduce stock by 1, not by fractions.

On 7 February 2017 at 11:57, Ignacio Foche <notifications@github.com> wrote:

ok, we'll remove the decimal point. Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/EyeSeeTea/SurveillanceMyanmarApp/issues/14#issuecomment-277965430>,
or mute the thread
