### ISSUE TITLE
Stock Control_Status

### ISSUE THREAD

**Issue by MonSuYee** [EyeSeeTea/SurveillanceMyanmarApp#15]
We will drop the Status line.

**Comment by ifoche** [comment]
It was more or less difficult to add this feature. You don't want it because it's not clear its meaning or it's just that you don't need it?

**Comment by rodmelia** [comment]
I will suggest to keep it - if we need to change the notation/ flags, we can.
Otherwise we can hide it.

**Comment by krosecrans** [comment]
We had discussed with Rodolfo at some point to drop the status line (will have to check notes)--the issue is that the minimum number of stock varies by region, season, and other factors and so we cannot just set one limit for all volunteers. We thought it was too difficult to tackle with this first version, but may try in the future. I suggest we hide.

**Comment by rodmelia** [comment]
Ok - let's hide it.

We can talk about some more elaborate logic for this while in Yangon

R
