### ISSUE TITLE
Buddybuild_screenshots

### ISSUE THREAD

**Issue by MonSuYee** [EyeSeeTea/SurveillanceMyanmarApp#18]
Buddybuild_screenshots are not coming to this waffle page anymore; am I doing it wrong?

**Comment by ifoche** [comment]
No, you're doing well. There's a 10 screenshot-per-release limit on the buddybuild account we're using. We've probably reached that limit. If you can just take the screenshot with your phone, and manually upload it to a waffle issue, that would be great. Otherwise, if find it complicated to upload the screenshot, please just create the waffle card and send me the screenshot by email, so I will attach it for you...or if it's something that can can wait for the next release, we will have 10 more screenshots once a new release will be generated

**Comment by ifoche** [comment]
Closing this as it's not really an issue, right?

**Comment by MonSuYee** [comment]
OK. Thank you
