### ISSUE TITLE
A different error message_Samsaung J7

### ISSUE THREAD

**Issue by MonSuYee** [EyeSeeTea/SurveillanceMyanmarApp#20]
One of our members using Samsaung J7 got a message saying Malaria App is using a lot of data, please uninstall it, kind of like that. She doesn't remember the exact message, but she will make a screenshot when she gets it another time. Me and Kathryn don't get that message. Thought you should know.

**Comment by ifoche** [comment]
Ok. Thanks. We'll wait for that picture in order to figure out the reason. It's quite strange as the release is not yet connected to the remote server, so it should say anything about data...but let's wait for it to happen again. Thanks for reporting. I'll keep this issue still open for a while just in case.

**Comment by rodmelia** [comment]
Closing old issue
