### ISSUE TITLE
Invalid Message for Ph No

### ISSUE THREAD

**Issue by MonSuYee** [EyeSeeTea/SurveillanceMyanmarApp#3]
The "Invalid Message for Phone Number" keeps popping out from the start of typing in the number. Can it occour only after typing?

**Comment by ifoche** [comment]
@MonSuYee the validation is taking place when you type following the "type event". There's no "I've finished typing event", because always you can decide to continue typing and Android cannot know in advance what you are going to do...but maybe we can put some kind of delay in the event treatment, so if a new "type event" arrives during the first second after the event occurs, we cancel the first event treatment...I think that could work...In that case, only if you type slower than 1 key per second you would see the message. Does that make sense for you?

**Comment by MonSuYee** [comment]
Yes, Ignacio, I think this will work for the problem. Thank you.
