### ISSUE TITLE
Skipping Ph Number

### ISSUE THREAD

**Issue by MonSuYee** [EyeSeeTea/SurveillanceMyanmarApp#4]
When I don't have a phone number to type in, I can't scroll down to choose the "Patient's residence" like I usually do when I use other apps. Is scrolling a thing we can apply to this app?

**Comment by ifoche** [comment]
@MonSuYee the scroll is there, but to make the scroll work you cannot click on a textfield (because the textfield is capturing the click event to allow you type on it). Maybe we can spend some time trying to make those 2 events to work together without conflicts. What do you think? Does it worth the pain of spending some time making the scroll work also starting from outside the textfields or do you think people will understand after some clicks that scroll cannot be done from a textfield?

**Comment by MonSuYee** [comment]
Yeah, I see.

It is that I would normally scroll down after typing on the current
textfield (while the cursor is still in the current textfield) to skip the
next field and get to the one after next. I think other people will also do
this. The norm is expected to be that the patients don't have a phone
number, and the volunteers will be frequently skipping phone number field.

I think an attractive alternative is to have the Address (the Patient's
residence) comes first. It would save the number of clicks they have to do
and consequently their confusion. (Many volunteers are expected to not
being used to touchscreen phones, so the simpler the better).

Please let me know what you think, Ignacio.
